# Generated by Django 5.2.11 on 2026-03-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='icon_image_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='アイコン画像パス'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_bio',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='プロフィール文'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
