# Generated by Django 5.2.11 on 2026-03-17 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("019cfa1c-96a6-7f8c-a936-c4cb6f97ee33"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("019cfa1c-96a5-75f4-875a-6a1a32380a50"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
