# Generated by Django 5.2.11 on 2026-03-17 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_emailverificationtoken_token_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("019cfb96-68a5-7ba8-a5fd-eddd18566294"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("019cfb96-68a4-7ddf-8e37-0bec95a2b705"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
