# Generated by Django 5.2.11 on 2026-03-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_github_url_user_icon_image_path_and_more"),
        ("profile", "0002_alter_userskill_skill_alter_userskill_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                through="profile.UserSkill",
                to="profile.techskill",
                verbose_name="スキル",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="github_url",
            field=models.URLField(
                blank=True, default="", max_length=255, verbose_name="GitHub URL"
            ),
        ),
    ]
