# Generated by Django 5.2.11 on 2026-03-14 23:11

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'verbose_name': 'メール確認トークン', 'verbose_name_plural': 'メール確認トークン'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
        # 本番DBにカラムが存在しない場合も安全に通過できるよう IF EXISTS を使用
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='user', name='created_at'),
                migrations.RemoveField(model_name='user', name='github_url'),
                migrations.RemoveField(model_name='user', name='icon_image_path'),
                migrations.RemoveField(model_name='user', name='profile_bio'),
                migrations.RemoveField(model_name='user', name='updated_at'),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS created_at",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS github_url",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS icon_image_path",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS profile_bio",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_user DROP COLUMN IF EXISTS updated_at",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 14, 23, 11, 12, 482230, tzinfo=datetime.timezone.utc), verbose_name='登録日時'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='トークン'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_token', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='メール確認後に True になります', verbose_name='アクティブ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='スタッフ権限'),
        ),
    ]
