# Generated by Django 5.2.11 on 2026-03-15 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_username_to_user"),
        ("accounts", "0003_alter_emailverificationtoken_options_and_more"),
    ]

    operations = []
