# Generated by Django 5.2.11 on 2026-03-17 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_emailverificationtoken_token_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("019cfba2-3f86-763e-843b-e6c4ac9ee483"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("019cfba2-3f85-730d-8a54-843f0d405c84"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
