# Generated by Django 5.2.11 on 2026-03-17 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_emailverificationtoken_token_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("019cfbb8-55d1-7574-aaf6-fe323132dc60"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("019cfbb8-55d0-795c-8403-bfc2020902d9"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
