# Generated by Django 5.2.11 on 2026-03-18 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_emailverificationtoken_token_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.UUIDField(
                default=uuid.UUID("019cff89-8ff2-71dd-8d72-329f06e7d9d8"), unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("019cff89-8ff1-741e-9912-e4925c9cdbbf"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
