# Generated by Django 5.2.11 on 2026-03-17 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_personalchatroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddConstraint(
            model_name='personalchatroom',
            constraint=models.CheckConstraint(condition=models.Q(('user1__lt', models.F('user2'))), name='personal_chatroom_user1_lt_user2'),
        ),
    ]
