# Generated by Django 5.2.11 on 2026-03-15 03:11

import django.db.models.deletion
import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TechCategories",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TechSkills",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VibeTags",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=project.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("opening", "開始前"),
                            ("ongoing", "進行中"),
                            ("completed", "完了"),
                        ],
                        default="opening",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "project_image_path",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedProjects",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=project.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projects",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "user")},
            },
        ),
        migrations.AddField(
            model_name="projects",
            name="saved_by_users",
            field=models.ManyToManyField(
                related_name="saved_projects",
                through="project.SavedProjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ProjectsCategories",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=project.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projects",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.techcategories",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "category")},
            },
        ),
        migrations.AddField(
            model_name="projects",
            name="categories",
            field=models.ManyToManyField(
                related_name="projects",
                through="project.ProjectsCategories",
                to="project.techcategories",
            ),
        ),
        migrations.CreateModel(
            name="ProjectsTechnologies",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=project.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projects",
                    ),
                ),
                (
                    "technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.techskills",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "technology")},
            },
        ),
        migrations.AddField(
            model_name="projects",
            name="technologies",
            field=models.ManyToManyField(
                help_text="プロジェクトを通して学びたい技術",
                related_name="projects",
                through="project.ProjectsTechnologies",
                to="project.techskills",
            ),
        ),
        migrations.CreateModel(
            name="ProjectsVibes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=project.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projects",
                    ),
                ),
                (
                    "vibe_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.vibetags",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "vibe_tag")},
            },
        ),
        migrations.AddField(
            model_name="projects",
            name="vibe_tags",
            field=models.ManyToManyField(
                related_name="projects",
                through="project.ProjectsVibes",
                to="project.vibetags",
            ),
        ),
    ]
