# Generated by Django 5.2.11 on 2026-03-18 09:06

import django.db.models.deletion
import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # CREATE TABLE IF NOT EXISTS を使うことで、
        # 本番 DB（既存テーブルあり）でもクリーンな DB でも両方動作する。
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "project_application" (
                            "id"           uuid         NOT NULL PRIMARY KEY,
                            "status"       varchar(20)  NOT NULL DEFAULT 'pending',
                            "created_at"   timestamptz  NOT NULL,
                            "applicant_id" uuid         NOT NULL
                                REFERENCES "accounts_user" ("id")
                                DEFERRABLE INITIALLY DEFERRED,
                            "project_id"   uuid         NOT NULL
                                REFERENCES "project_project" ("id")
                                DEFERRABLE INITIALLY DEFERRED
                        );
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM pg_constraint
                                WHERE conname = 'project_application_project_id_applicant_id_uniq'
                            ) THEN
                                ALTER TABLE "project_application"
                                    ADD CONSTRAINT "project_application_project_id_applicant_id_uniq"
                                    UNIQUE ("project_id", "applicant_id");
                            END IF;
                        END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "project_application";',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Application',
                    fields=[
                        ('id', models.UUIDField(default=project.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                        ('status', models.CharField(choices=[('pending', '申請中'), ('accepted', '承認済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='ステータス')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                        ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='project.project', verbose_name='プロジェクト')),
                    ],
                    options={
                        'verbose_name': '参加申請',
                        'verbose_name_plural': '参加申請',
                        'unique_together': {('project', 'applicant')},
                    },
                ),
            ],
        ),
    ]
