# Generated by Django 5.2.11 on 2026-03-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_add_project_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='参加ペース'),
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='メッセージ'),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ポートフォリオURL'),
        ),
        migrations.AddField(
            model_name='application',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='希望役割'),
        ),
    ]
