# Generated by Django 5.2.11 on 2026-03-20 08:06

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_auto_20260320_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="projecttechnology",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="projectvibe",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="savedproject",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
